commit 1
Masiaka8/Prestashop_Diplom_QA22_Maksim_Shestozub pull request #1
Opened 2023-02-24 15:52 UTC by Masiaka8

![Снимок экрана 2023-02-24 184038](https://user-images.githubusercontent.com/114669783/221224277-8446385a-a5a5-4a46-ae95-0d08a795353f.png)

2023-02-24 15:58 UTC, Masiaka8 commented
как мне казалось я ничего не пропустил с Lombok, но нет

2023-02-24 17:14 UTC, Masiaka8 commented
![Снимок экрана 2023-02-24 201300](https://user-images.githubusercontent.com/114669783/221244120-45b7fd52-fc5b-4848-9325-4752287aa7fc.png)
![Снимок экрана 2023-02-24 201316](https://user-images.githubusercontent.com/114669783/221244132-867e0bd7-78a0-4cbf-95ab-6f72e2e81a23.png)
![Снимок экрана 2023-02-24 201341](https://user-images.githubusercontent.com/114669783/221244149-37e9e4cf-a271-46ed-9266-455c45a15198.png)

2023-02-25 12:39 UTC, voropa requested changes

2023-02-25 12:39 UTC, voropa commented on pom.xml
> +            <version>0.15</version>
Чего такая древняя версия. 1.0.2 сейчас актуальная, работает нормально

2023-02-25 12:39 UTC, voropa commented on src/test/java/dataModels/User.java
> +    public User() {
Зачем вам тут пустой конструктор, если вы builder используете, вот поэтому и ошибка при запуске

2023-02-25 12:39 UTC, voropa commented on src/test/java/elements/Input.java
> +    private final static String INPUT_LOCATOR = "#%s";
Какой смысл делать такую "пустую" шаблонную строку. 
Луше сразу в методе setValue() делать driver.findElement(By.id(label); 
и не использовать шаблонную строку

2023-02-25 12:39 UTC, voropa commented on src/test/java/modals/newUserModal.java
> +public class newUserModal extends BaseModal {
Названия классов в java должны быть с большой буквы

2023-02-25 12:39 UTC, voropa commented on src/test/java/pages/AuthenticationOnePage.java
> +public class AuthenticationOnePage extends BasePage{
Лексически звучит некрасиво, лучше назвать класс AuthenticationFirstStepPage и потом второй класc AuthenticationSecondStepPage

2023-02-25 12:39 UTC, voropa commented on src/test/java/pages/BasePage.java
> +    public WebDriver driver;
Зачем драйвер тут public? Он же предполагается использоваться только внутри страниц, так сделайте его protected

2023-02-25 12:39 UTC, voropa commented on src/test/java/pages/HomePage.java
> +    private static final By WAIT_ITEM_CART = By.cssSelector(".ajax_cart_product_txt.unvisible[style = 'display: inline;']");
Не надежный локатор как по мне. 
.ajax_cart_product_txt.unvisible[style = 'display: inline;']
Переделайте его

2023-02-25 12:39 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +        //userPassword = faker.internet().password();
почему закоментировано?

2023-02-25 12:39 UTC, voropa commented on src/test/java/tests/RegistrationTest.java
> +    public void newUserRegistrationTest(User testUser){
не совсем понимаю зачем тут входной аргумент User testUser. вы же его не передаете нигде, и тест не data-driven

2023-02-25 12:39 UTC, voropa commented on src/test/java/tests/RegistrationTest.java
> +        User.builder()
А какой смысл от этого кода? Вы создаете user'a, но никуда его не сохраняете в обьект/ппеременную

2023-02-25 12:42 UTC, voropa commented
> ![Снимок экрана 2023-02-24 201300](https://user-images.githubusercontent.com/114669783/221244120-45b7fd52-fc5b-4848-9325-4752287aa7fc.png) ![Снимок экрана 2023-02-24 201316](https://user-images.githubusercontent.com/114669783/221244132-867e0bd7-78a0-4cbf-95ab-6f72e2e81a23.png) ![Снимок экрана 2023-02-24 201341](https://user-images.githubusercontent.com/114669783/221244149-37e9e4cf-a271-46ed-9266-455c45a15198.png)

Что-то странное вы делаете, все намного проще:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/14195681/221357337-2217d8d4-3d77-424d-bbf4-388bdb281506.png">

<img width="480" alt="image" src="https://user-images.githubusercontent.com/14195681/221357346-6a83b1b2-1744-49e9-b3d3-4f96964e6d55.png">

2023-02-27 17:30 UTC, Masiaka8 commented
![Снимок экрана 2023-02-27 201422](https://user-images.githubusercontent.com/114669783/221638665-569191fe-9e1c-42d2-8096-0e947835aa79.png)

2023-02-27 17:50 UTC, voropa commented
> ![Снимок экрана 2023-02-27 201422](https://user-images.githubusercontent.com/114669783/221638665-569191fe-9e1c-42d2-8096-0e947835aa79.png)

Так builder()  - это же метод, нужно с маленькой буквы его писать, а вы с Большой пишете, вот и подчеркивает красным. У меня в примере же работает, когда все правильно написано

2023-03-02 07:08 UTC, voropa approved these changes

2023-03-02 14:15 UTC, merged