Commit 4
Masiaka8/Prestashop_Diplom_QA22_Maksim_Shestozub pull request #2
Opened 2023-03-10 01:11 UTC by Masiaka8

Есть некоторые вопросы. Пару тестов всегда падают из-за странных шрифтов на сайте, при это я их подогнал и вручную тесты перестали падать но через mvn всё равно падают на асерте. Скриншоты делаются половины экрана и ошибку не захватывают, хотя driver maximize прописано.

2023-03-10 01:14 UTC, Masiaka8 commented
![photo_2023-03-10_04-12-25](https://user-images.githubusercontent.com/114669783/224197803-e2fba57d-2348-4f2e-b112-a669141d0952.jpg)
Если с шрифтами ещё можно понять то что б 1 было не равно 1 не ясно что там у них на сайте (пробелы и тд проверял)

2023-03-10 10:39 UTC, voropa requested changes

2023-03-10 10:39 UTC, voropa commented on regressiveTest.xml
> +        <parameter name="browser" value="Chrome"></parameter>
У вас не получиться так запустить тесты на 2х браузерах, вы же параметр browser получаете из командной строки mvn, а этот <parameter name="browser" value="Chrome"></parameter> нигде не споользуетсяс в тестах. Соотвественно, при запуске этог xml файла у вас запустяться 2 одинаковых процесса на одном и том же браузере.

2023-03-10 10:39 UTC, voropa commented on src/test/java/pages/BasePage.java
> +    protected final Logger logger = LogManager.getLogger(this.getClass().getName());
По java code convention константы, поля и переменные в классе должны быть обьявлены до методов и конструктора, а у вас logger. наоборот в самом конце

2023-03-10 10:39 UTC, voropa commented on src/test/java/pages/MyAccountPage.java
> +        logger.info("Message is displayed");
А какой именно Message is displayed? Добавьте больше конкретики в логи. От такого сообщения толку 0

2023-03-10 10:39 UTC, voropa commented on src/test/java/pages/MyAccountPage.java
> +        logger.info("Message is displayed");
Тут тоже

2023-03-10 10:39 UTC, voropa commented on src/test/java/pages/ShoppingCartPage.java
> +    private final static By PROCESSED_TO_CHECKOUT_BUTTON= By.xpath("//*[@class='button btn btn-default standard-checkout button-medium']");
Очень плохе локаторы для этих конопок, которы ссылаются на полный спписок классов элемента и очень похожи друго на друга. Если хоть один класс поменяется / добавться, то они перестанут работать. Переделайте

2023-03-10 10:39 UTC, voropa commented on src/test/java/pages/ShoppingCartPage.java
> +        logger.debug("Item price {}", getItemPrice());
Почему .debug()? 
О, и вы еще реккурсивно внутри лога вызываете этот же метод. Так делать точно не нужно.
Если хотите залогровать значение полученного price, то делается это вот так:
logger.info("Getting item price");
String itemPrice = driver.findElement(ITEM_PRICE_LOCATOR).getText();
logger.info("Price value: {}", itemPrice);

2023-03-10 10:39 UTC, voropa commented on src/test/java/pages/WomenPage.java
> +        logger.debug("Message {}", getResultSearchMassageText());
И тут рекурсия в логе. Перепроверьте все логи, где подобные действия

2023-03-10 10:39 UTC, voropa commented on src/test/java/tests/CartTest.java
> +        Assert.assertTrue(productDetailsPage.addedItemMessage());
То, что появилоось сообщение, еще не  гарантирует, что  товар добавился. В такомм тесте нужно перехоодит ьв корзину после добавления товара и проверять, что там в списке есть добавленный товар

2023-03-10 10:39 UTC, voropa commented on src/test/java/tests/FilterTest.java
> +                {Arrays.asList("Leatherette bags in stock","Stylish leather bags in stock","Leather bags in stock",
А какой смысл от этого data-provider в этом тесте, если в нем только один массв элементов? Т.е. тест будет запускаться только один раз

2023-03-10 10:39 UTC, voropa commented on src/test/java/tests/WishListTest.java
> +        Assert.assertEquals(myWishListPage.getAmountOfItem(), 1);
Хорошо бы проверить не просто коллиичество  товаров, а еще и конкретное название товара, который добавился

2023-03-10 10:41 UTC, voropa commented
> ![photo_2023-03-10_04-12-25](https://user-images.githubusercontent.com/114669783/224197803-e2fba57d-2348-4f2e-b112-a669141d0952.jpg) Если с шрифтами ещё можно понять то что б 1 было не равно 1 не ясно что там у них на сайте (пробелы и тд проверял)

Все верно. У вас метод myWishListPage.getAmountOfItem() возвращает String и вы его в ассерте сравнваете с 1 (int). вот и падает ассерт, потому что разные типы данных. Вам нужно првести их к одному типу либо string либо int

2023-03-10 11:18 UTC, Masiaka8 commented on regressiveTest.xml
> +        <parameter name="browser" value="Chrome"></parameter>
нет, там запускается 2 хрома просто, я и не менял

2023-03-10 12:25 UTC, voropa commented on regressiveTest.xml
> +        <parameter name="browser" value="Chrome"></parameter>
Ну так а какой смысл запускать в параллель одни и те же тесты на одном и том же браузере?)

2023-03-10 19:21 UTC, voropa requested changes

2023-03-10 19:21 UTC, voropa commented on src/test/java/tests/CartTest.java
> +        Assert.assertEquals(shoppingCartPage.getItemName(), "Faded Short Sleeve T-shirts");
У вас же есть выше константаа с именен товара ITEM_NAME, используйте ее тут, зачем заново хардкодить название

2023-03-10 19:21 UTC, voropa commented on src/test/java/tests/FilterTest.java
> +    public void filterTest() {
Лучше конечно все таки сделать этот тест data-driven и проверять не один фильтр, как у вас сейчас, а несколько. Там же в каталооге их много)

2023-03-10 19:51 UTC, Masiaka8 commented on src/test/java/tests/FilterTest.java
> +    public void filterTest() {
Я просто подумал 1 тест проверил 1 функцию =)

2023-03-12 12:05 UTC, voropa requested changes

2023-03-12 12:05 UTC, voropa commented on src/test/java/pages/WomenPage.java
> +    public void setFilter(String filterName) {
Так а почему этот агрумент String filterName не используется нигде внутри метода? У вас же  просто выбираются все фильтры подряд, а должен только один конкретный по  имени

2023-03-12 12:07 UTC, voropa commented on src/test/java/tests/WishListTest.java
> +        Assert.assertEquals(myWishListPage.getAmountOfItem(), 1);
Все еще актуальный коментарий

2023-03-13 18:00 UTC, voropa requested changes

2023-03-13 18:00 UTC, voropa commented on src/test/java/tests/BaseTest.java
>          driver.get("http://prestashop.qatestlab.com.ua/en/");
Вы же читаете BASE_URL из config.properties, так почему не используете его тут?
public final static String BASE_URL = PropertyReader.getProperty("base_url");

2023-03-13 18:01 UTC, voropa reviewed
А где README файл с описанием проекта, чеклистом и т д?

2023-03-13 20:38 UTC, voropa commented on smokeTest.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Смоук тест  при запуске падает:
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/14195681/224791472-28f8d684-2f9b-4de6-add2-8c5f934e4573.png">

Вот тут ElementNotInterractiveException Судя по скриншоту, пытается нажать кнопку, которая вниизу экрана, нужно скролить к ней перед кликом

2023-03-13 21:02 UTC, Masiaka8 commented on smokeTest.xml
> +<?xml version="1.0" encoding="UTF-8"?>
![Снимок экрана 2023-03-14 000105](https://user-images.githubusercontent.com/114669783/224831484-fdd61eab-28d8-4877-87d5-961919bdb846.png)
поправил

2023-03-13 21:04 UTC, voropa requested changes
Там проблема не в ожидании, а в том, что элемент находится за пределами видимой области экрана, и нужно делать scrollIntoView в нему, прежде, чем кликать

2023-03-13 21:04 UTC, voropa commented on src/test/java/pages/ShoppingCartPage.java
> +    public void WaitQWER(){
Это что за название метода?

2023-03-13 21:06 UTC, Masiaka8 commented on src/test/java/pages/ShoppingCartPage.java
> +    public void WaitQWER(){
нечайно отправил и удалил уже. я поменял локатор там и теперь проходит без ошибок

2023-03-13 21:07 UTC, voropa commented on src/test/java/pages/ShoppingCartPage.java
> +    public void WaitQWER(){
Там дело не в локаторе, почитайте комментарий выше

2023-03-13 21:08 UTC, Masiaka8 commented on src/test/java/pages/ShoppingCartPage.java
> +    public void WaitQWER(){
![Снимок экрана 2023-03-14 000741](https://user-images.githubusercontent.com/114669783/224832724-f86302ca-ef83-4925-8163-299eebf1de1c.png)

2023-03-13 21:10 UTC, voropa commented on src/test/java/pages/ShoppingCartPage.java
> +    public void WaitQWER(){
Ладно, магия, у меня тоже работает теперь...

2023-03-13 21:11 UTC, voropa approved these changes

2023-03-13 21:12 UTC, merged